import 'package:freezed_annotation/freezed_annotation.dart';
import '../../domain/entities/user.dart';

part 'user_model.freezed.dart';
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  const factory UserModel({
    required String id,
    required String name,
    required String email,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, dynamic> json) =>
      _$UserModelFromJson(json);
}

extension UserModelX on UserModel {
  User toEntity() => User(id: id, name: name, email: email);
}

//What this is:
//- UserModel is the data layer representation — it knows about JSON
//- @freezed + part files will be generated by build_runner
//- toEntity() converts UserModel → User (domain entity) — this is the mapping between layers
//- The domain layer never touches UserModel directly
